# Generated by Django 5.2.16 on 2026-07-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrendatarios', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('valor_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriendos', to='arrendatarios.arrendatario')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriendos', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Arriendo',
                'verbose_name_plural': 'Arriendos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entrega', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('RETENIDA', 'Retenida'), ('DEVUELTA', 'Devuelta'), ('USADA_POR_DANOS', 'Usada por danos')], default='RETENIDA', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='arriendos.arriendo')),
            ],
            options={
                'verbose_name': 'Garantia',
                'verbose_name_plural': 'Garantias',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=30)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=40)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ATRASADO', 'Atrasado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='arriendos.arriendo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha_vencimiento'],
                'constraints': [models.UniqueConstraint(fields=('arriendo', 'periodo'), name='pago_unico_por_arriendo_periodo')],
            },
        ),
    ]
