# Generated by Django 5.2.16 on 2026-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarrendamiento',
            name='estado_pago',
            field=models.CharField(choices=[('SIN_SELECCIONAR', 'Sin seleccionar'), ('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado')], default='SIN_SELECCIONAR', max_length=30),
        ),
        migrations.AddField(
            model_name='solicitudarrendamiento',
            name='metodo_pago',
            field=models.CharField(choices=[('SIN_SELECCIONAR', 'Sin seleccionar'), ('PAYPAL', 'PayPal'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('SITIO', 'Pagar en el sitio')], default='SIN_SELECCIONAR', max_length=30),
        ),
        migrations.AddField(
            model_name='solicitudarrendamiento',
            name='observaciones_pago',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudarrendamiento',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
