# Generated by Django 5.2.16 on 2026-07-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bien', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DANADO', 'Danado')], default='BUENO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Inventario de habitacion',
                'verbose_name_plural': 'Inventario de habitaciones',
                'ordering': ['habitacion__codigo', 'nombre_bien'],
            },
        ),
    ]
